export type MorphTargetMapper = { [key: string]: MorphTargetStandardKey };
export type MorphTargetStandardKey =
    'mouthRollLower' |
    'browOuterUp_L' |
    'mouthSmile_L' |
    'jawRight' |
    'eyeLookOut_L' |
    'mouthFunnel' |
    'mouthUpperUp_R' |
    'browDown_L' |
    'jawLeft' |
    'mouthLowerDown_L' |
    'noseSneer_R' |
    'jawForward' |
    'mouthLowerDown_R' |
    'browInnerUp' |
    'mouthRollUpper' |
    'mouthStretch_R' |
    'mouthPucker' |
    'eyeBlink_L' |
    'mouthUpperUp_L' |
    'mouthShrugUpper' |
    'eyeLookIn_R' |
    'noseSneer_L' |
    'mouthFrown_L' |
    'cheekSquint_L' |
    'eyeLookDown_L' |
    'mouthDimple_L' |
    'mouthFrown_R' |
    'eyeLookIn_L' |
    'eyeLookOut_R' |
    'mouthLeft' |
    'mouthStretch_L' |
    'mouthPress_L' |
    'mouthDimple_R' |
    'eyeWide_R' |
    'browDown_R' |
    'eyeLookUp_R' |
    'eyeBlink_R' |
    'cheekSquint_R' |
    'mouthRight' |
    'eyeLookDown_R' |
    'eyeLookUp_L' |
    'eyeSquint_L' |
    'jawOpen' |
    'browOuterUp_R' |
    'mouthClose' |
    'mouthShrugLower' |
    'eyeWide_L' |
    'tongueOut' |
    'eyeSquint_R' |
    'cheekPuff' |
    'mouthPress_R' |
    'mouthSmile_R';
