name: CI Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Setup node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: pnpm
        
    - name: Install deps
      run: pnpm install
    
    - name: Test Build
      run: pnpm run build:test

    - name: Test in Electron
      run: pnpm run test:ci
        